# Generated by Django 5.1.7 on 2025-03-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_countrydata_city_weatherdata_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='precip_1h',
        ),
    ]
