# Generated by Django 5.1.7 on 2025-03-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_weatherdata_precip_1h'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='humidity',
            field=models.FloatField(default=0),
        ),
    ]
